### ISSUE TITLE
please provide binarys for all common architectures

### ISSUE THREAD

**Issue by chanjala** [kingk85/uFTP#1]
i miss arm (boards like raspberry pi or odroid-xu series ) and mips (for routers with openwrt), maybe also ppc and ppc64. you can use qemu-system and debian for tests and compilings, its quite simple to setup, and if you want i can help you or provide build server compute time...

thanks in advance

**Comment by kingk85** [comment]
Hello,

I am currently working on the TLS implementation I am quite busy at this moment, if you could provide builds for different architectures would be really appreciated, message me when you are ready I will upload the binaries.

Best Regards
Ugo
