### ISSUE TITLE
Missed option to set ports range for client connections.

### ISSUE THREAD

**Issue by an-eternity** [kingk85/uFTP#13]
uFTP server uses any arbitrary port number for client connections, which is very inconvenient or even not acceptable in some cases...
Documentation does not contain any related information.
This option should provide an opportunity to specify an exact ports range uFTP server will use for clients connections, e.g., from TCP 1024 to TCP 1124, so that server admin can tune up firewall and another software running on the server respectively. Apparently, such option is not available...

**Comment by kingk85** [comment]
Thank you for your comment, unfortunately this functionality is not
available but I will integrate it soon, should be quite easy to add, I am
agree with you it’s a very important feature.

Best regards
Ugo

Il giorno lun 20 giu 2022 alle 10:11 Eternity ***@***.***> ha
scritto:
