### ISSUE TITLE
Is not compatible with modern ssh client

### ISSUE THREAD

**Issue by DoubleBoba** [kingk85/uFTP#14]
I'm very disappointed with this piece of software, because it simply unusable for me. I tried to use it with FileZilla, Cyberduck and builtin python ftp lib and they all cannot even list directories because of lack of EPSV command support. I moved to another solution, but i still have question: how am i supposed to  use uFTP? What clients are compatible?

**Comment by kingk85** [comment]
Hello,
Thank you for your email.
I can confirm EPSV is not yet supported, the project has been idle for 3
years but I am going to improve it in 2023, I have been extremely busy in
the last few years working 14/h day 7/7.
For all other functions it works, I think you have some setup issue if you
are not able to use it with filezilla or other ftp client.

Regards
Ugo



Il giorno sab 5 nov 2022 alle ore 11:48 Tamtaradam ***@***.***>
ha scritto:

**Comment by llothar** [comment]
Good to hear, i hope you find the time. Please also fix the compilation errors and move from make to cmake as build system.
Was so happy to find a small simple ftp for testing but also have to move to another solution now.

**Comment by kingk85** [comment]
I have enabled EPSV command, need to be tested
