### ISSUE TITLE
an crash when change the packet shuffle

### ISSUE THREAD

**Issue by CodeLogicError** [kingk85/uFTP#20]
when do not send username message and send all other message 
![a7a802ce619e20faf5b3b41eac39848](https://github.com/kingk85/uFTP/assets/97520427/ff859bfb-9aa0-4b4b-871a-7fbd774fc9e8)

**Comment by kingk85** [comment]
I could not reproduce it, standard behavior is that if the user is not logged in an error message is sent to every and each command that require login
