### ISSUE TITLE
Unable to Retrieving directory listing

### ISSUE THREAD

**Issue by mateors** [kingk85/uFTP#21]
I did everything as guided in https://www.uftpserver.com/wiki/uftp-server-installation **Option 2 install from binary**
But still its not working.

here is the log received from FileZilla FTP client.
```
Status:	Connecting to 209.126.12.223:21...
Status:	Connection established, waiting for welcome message...
Status:	Plain FTP is insecure. Please switch to FTP over TLS.
Status:	Logged in
Status:	Retrieving directory listing...
Command:	PWD
Response:	257 "/" is your current location
Command:	TYPE I
Response:	200 TYPE is now 8-bit binary
Command:	PASV
Response:	227 Entering Passive Mode (209,126,12,223,54,46)
Command:	LIST
Error:	Connection timed out after 20 seconds of inactivity
Error:	Failed to retrieve directory listing
Status:	Disconnected from server
```

**Comment by 0hip** [comment]
Running fine here (Windows 10 home : uFTP.exe + Filezilla 3.65.0)
![image](https://github.com/kingk85/uFTP/assets/90657954/27c61d4f-32c3-41fe-9666-89c860b1985b)

**Comment by mateors** [comment]
@0hip Thank you for your response, I was using linux(ubuntu 23.04) via WSL2. Also tried in the cloud but no luck. I think uFTP is not production ready yet. So I am finding another solution based on golang.

**Comment by 0hip** [comment]
https://github.com/hfiref0x/LightFTP
Maybe you can give it a try. It also has a config file

**Comment by mateors** [comment]
@0hip thank you for your recommendation, I am grateful to you.
