### ISSUE TITLE
Building fails

### ISSUE THREAD

**Issue by bojan385** [kingk85/uFTP#24]
Hardware Raspberry Pi 3B+
Raspberry Pi OS (64-bit) with desktop
Release date: March 15th 2024
System: 64-bit
Kernel version: 6.6
Debian version: 12 (bookworm)
gcc (Debian 12.2.0-14) 12.2.0

Building fails with:

./library/connection.c:964:115: error: ‘struct sockaddr_in’ has no member named ‘sin6_addr’; did you mean ‘sin_addr’?
  964 |                         if(inet_ntop(AF_INET6, &ftpData->clients[availableSocketIndex].client_sockaddr_in.sin6_addr, ftpData->clients[availableSocketIndex].clientIpAddress, sizeof(ftpData->clients[availableSocketIndex].clientIpAddress)))
      |                                                                                                           ^~~~~~~~~
      |                                                                                                           sin_addr
./library/connection.c:966:163: error: ‘struct sockaddr_in’ has no member named ‘sin6_port’; did you mean ‘sin_port’?
  966 | [availableSocketIndex].clientPort = (int) ntohs(ftpData->clients[availableSocketIndex].client_sockaddr_in.sin6_port);
      |                                                                                                           ^~~~~~~~~
      |                                                                                                           sin_port
./library/connection.c:971:115: error: ‘struct sockaddr_in’ has no member named ‘sin6_addr’; did you mean ‘sin_addr’?
  971 |                         if(inet_ntop(AF_INET6, &ftpData->clients[availableSocketIndex].server_sockaddr_in.sin6_addr, ftpData->clients[availableSocketIndex].serverIpAddress, sizeof(ftpData->clients[availableSocketIndex].serverIpAddress)))
      |                                                                                                           ^~~~~~~~~
      |                                                                                                           sin_addr
make: *** [Makefile:91: connection.o] Error 1

**Comment by kingk85** [comment]
Hello 

try to comment this line in the Makefile and then compile 

ENABLE_IPV6_SUPPORT=-D IPV6_ENABLED

**Comment by bojan385** [comment]
It is commented, I dont need IPv6 support.

![image](https://github.com/kingk85/uFTP/assets/20319032/ae5e250a-ec4d-4e6b-b97a-492405f4c603)

![image](https://github.com/kingk85/uFTP/assets/20319032/69e29ee1-7a6e-4f31-9dca-7a94fb8cae5c)

**Comment by kingk85** [comment]
I will check asap, probably the define doesn't disable everything ipv6 related.

You can clone a previous revision in the meanwhile

**Comment by bojan385** [comment]
OK, thank You !

**Comment by kingk85** [comment]
Can you try again? 
I have left a define by mistake in  connection.c

**Comment by bojan385** [comment]
Yeah, now everything works OK.
Thank You.
I have been using Your uFTP server for a quite time now, for a few projects, and it is the best small and simple FTP server, kudos.

**Comment by kingk85** [comment]
Thank you for your feedback.
