### ISSUE TITLE
In active mode, Server is unresponsive, and the client is frozen

### ISSUE THREAD

**Issue by nekarose** [kingk85/uFTP#26]
In active mode, Server is unresponsive, and the client is frozen. Plz help me.

My case: 
(Window CMD, FTP) Connecion is OK, but when commanding "ls" or "dir", the server is unresponsive, and the client is frozen,
230 Login Ok.
ftp> ls
200 connection accepted
150 Accepted data connection
----------------> Client is frozen.
=> Is uFTP currently unstable in active mode? I need assistance!!!!!

**Comment by kingk85** [comment]
I have found the root cause, a missing flag to the port command broke the server. 
Try again with the updated source code.

**Comment by nekarose** [comment]
Thank you for soloving the problem!! It works well now.
