### ISSUE TITLE
 Run ordinary shell  script under arm64 

### ISSUE THREAD

**Issue by luqinlive** [kingk85/uFTP#4]
hi, I successfully compiled in a cross compilation environment ，but can't copy to system env folder(cp: can't create '/sbin/uFTP': Read-only file system),then  run under script use ./uFTP  ,  uutput is as follows， no background process  :

Hello uFTP server v2.2.0 RC1 starting..

Reading configuration from
 -> ./uftpd.cfg
so， How do I run processes in the background in this case ，thanks.

**Comment by kingk85** [comment]
Hello,

Both commands should be sent with root privileges.
eg. sudo ./uFTP

or login as root with the "su" command before sending the commands.

Regards
Ugo

Il giorno ven 10 apr 2020 alle ore 06:48 luqin <notifications@github.com>
ha scritto:
