### ISSUE TITLE
How could I build a static compilation version？

### ISSUE THREAD

**Issue by Exspectate** [kingk85/uFTP#6]
Thank you for your wonderful work. Now I need a static compilation version of uFTP, and I did these:

1. I add -static option in line 49 of Makefile 

2. I disabled [ENABLE_OPENSSL_SUPPORT] in line 25,26 of  Makefile

3. make, and then get a new uFTP program

but when I execute this, I got this output:
[
Hello uFTP server v2.2.0 RC1 starting..

Reading configuration from 
 -> /etc/uftpd.cfg
Segmentation fault
]

Could you help me with this? Thanks.

**Comment by Str1ker17** [comment]
Hello. I'm not uFTP maintainer; however, possibly your problem is not so difficult. First, please provide some info about your environment: processor architecture and bitness, compiler version, C library (this can be either glibc, uclibc or musl), Linux version.

**Comment by kingk85** [comment]
you can use musl, https://musl.libc.org I have never tried but it should work

**Comment by kingk85** [comment]
I will add the makefile commented commands for this since I think is an interesting option
