### ISSUE TITLE
Wrong permissions

### ISSUE THREAD

**Issue by HowToMeetLadies** [kingk85/uFTP#9]
> Set permissions and root restriction of the configuration file.
> 
> chown root:root /sbin/uFTP
> chown root:root /etc/uftpd.cfg
> chmod -rwx /etc/uftpd.cfg
**> chmod u+rwx /etc/uftpd.cfg**

Executable? *facepalm*

**Comment by kingk85** [comment]
Hello,

Thanks for the error report, I have updated the website.

Regards
Ugo

Il giorno lun 17 ago 2020 alle ore 16:45 Chris <notifications@github.com>
ha scritto:

**Comment by Ssmarsh** [comment]
- [ ]
